import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/HomeIndex.module.css'
import MainContainer from '../components/MainContainer'
import Home from '../components/Home'

const inter = Inter({ subsets: ['latin'], weights: [400, 500, 600, 700] })

export default function HomeIndex() {
  return (
    <>
      <Head>
        <title>Ahnaf`s Perosnal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <MainContainer>
          <Home />
        </MainContainer>
      </main>
    </>
  )
}
