import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/HomeIndex.module.css'
import MainContainer from '@/components/MainContainer'
import Navigation from '@/components/Navigation'

const inter = Inter({ subsets: ['latin'], weights: [400, 500, 600, 700] })

const BaseLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Ahnaf Ahamed | Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <MainContainer>
          {children}
          <Navigation/>
        </MainContainer>
      </main>
    </>
  )
}

export default BaseLayout;